version: '3.8'

services:
  hik-app:
    build: .
    container_name: hik-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "21:21"
      - "10000-10100:10000-10100"
    environment:
      - PORT=3000
      - FTP_PORT=21
      - PASV_URL=${PASV_URL:-77.237.245.47} # Default to VPS IP if not set
      - PASV_MIN=10000
      - PASV_MAX=10100
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./events.db:/app/events.db
      - ./ftp:/app/ftp
      - ./uploads:/app/uploads
      - ./vehicles:/app/vehicles
      - ./snapshots:/app/snapshots
