version: '3.8'

services:
  hik-app:
    build: .
    container_name: hik-app
    restart: unless-stopped
    ports:
      - "9000:3000"
      - "21:21"
      - "9100-9200:9100-9200"
    environment:
      - PORT=3000
      - FTP_PORT=21
      - PASV_URL=${PASV_URL:-77.237.245.47}
      - PASV_MIN=9100
      - PASV_MAX=9200
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data:/app/data
      - ./ftp:/app/ftp
      - ./uploads:/app/uploads
      - ./vehicles:/app/vehicles
      - ./snapshots:/app/snapshots
